# Generated by Django 3.0.8 on 2020-07-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('r', 'Rent'), ('s', 'Sale')], max_length=8),
        ),
    ]
